p8105_hw1_qc2337
================
2024-09-21

# hw1 Problem 1

First loaded the palmerpenguins package and load pemnguins dataset

``` r
library(palmerpenguins)
data("penguins", package = "palmerpenguins")
```

Second description of the penguins dataset using inline R code show
variable names, structure of the dataset, size of the dataset, mean
flipper length calculation

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
str(penguins)
```

    ## tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
    ##  $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
    ##  $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
    ##  $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
    ##  $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
    ##  $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
    ##  $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
    ##  $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean_flipper_length <- mean(penguins$flipper_length_mm, na.rm = TRUE)
mean_flipper_length
```

    ## [1] 200.9152

From the description code, we know that in the penguins dataset,
variable names include: `species`, `island`,
`bill_length_mm`,`bill_depth_mm`, `flipper_length_mm`, `body_mass_g`,
`sex`, `year`.

The size of the dataset includes: 344 rows and 8 columns.

The mean flipper length is 200.9152.

Make a scatterplot and save the scatterplot

``` r
library(ggplot2)
ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
    geom_point() + 
    labs(title = "Scatterplot of Flipper Length vs Bill Length by Species",
         x = "Bill Length (mm)",
         y = "Flipper Length (mm)")
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_qc2337_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("penguins_scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# hw1 Problem 2

This is code for the problem2 at P8105.

Loaded necessary packages (e.g. `tidyverse`) for problem 2.

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ lubridate 1.9.3     ✔ tibble    3.2.1
    ## ✔ purrr     1.0.2     ✔ tidyr     1.3.1
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Created `p2_df` as the data frame, comprised of:

- a random sample of size 10 from a standard Normal distribution

- a logical vector indicating whether elements of the sample are greater
  than 0

- a character vector of length 10

- a factor vector of length 10, with 3 different factor “levels”

``` r
  p2_df = 
    tibble(
      norm_samp = rnorm(n = 10),
      samp_g0 = norm_samp > 0,
      char_samp = letters [1:10],
      fact_samp = factor(rep(c("1", "2", "3"), length = 10))
    )
print(p2_df)
```

    ## # A tibble: 10 × 4
    ##    norm_samp samp_g0 char_samp fact_samp
    ##        <dbl> <lgl>   <chr>     <fct>    
    ##  1    0.480  TRUE    a         1        
    ##  2   -0.775  FALSE   b         2        
    ##  3    0.246  TRUE    c         3        
    ##  4   -0.402  FALSE   d         1        
    ##  5    1.73   TRUE    e         2        
    ##  6   -0.0161 FALSE   f         3        
    ##  7    0.664  TRUE    g         1        
    ##  8   -0.461  FALSE   h         2        
    ##  9    0.721  TRUE    i         3        
    ## 10   -0.990  FALSE   j         1

Take the mean of each variable in the `p2_df`

``` r
  mean_norm_samp = mean(pull(p2_df, norm_samp), na.rm = TRUE)
  mean_norm_samp 
```

    ## [1] 0.1200398

``` r
  mean_samp_g0 =  mean(pull(p2_df, samp_g0), na.rm = TRUE)
  mean_samp_g0
```

    ## [1] 0.5

``` r
  mean_char_samp = mean(pull(p2_df, char_samp), na.rm = TRUE)
```

    ## Warning in mean.default(pull(p2_df, char_samp), na.rm = TRUE): argument is not
    ## numeric or logical: returning NA

``` r
  mean_char_samp
```

    ## [1] NA

``` r
  mean_fact_samp = mean(pull(p2_df, fact_samp), na.rm = TRUE)
```

    ## Warning in mean.default(pull(p2_df, fact_samp), na.rm = TRUE): argument is not
    ## numeric or logical: returning NA

``` r
  mean_fact_samp
```

    ## [1] NA

I found that the `random sample of size 10` and `logical vector` works,
but `character vector` and `factor vector` doesn’t work.

Applies the `as.numeric` function to the logical, character, and factor
variables

``` r
numeric_samp_g0 = as.numeric(pull(p2_df, samp_g0))

numeric_char_samp = as.numeric(pull(p2_df, char_samp))

numeric_fact_samp = as.numeric(pull(p2_df, fact_samp))
```

I find that:

The logical variable turns into 2 numeric: `TRUE` becomes `1` and
`FALSE` becomes `0`.

The character variable turns to `NA` for all elements, R cannot
calculate the mean. So when I try to take the mean of character
variable, it shows warning message: argument is not numeric or logical:
returning NA.

The factor variable turns to numeric variable which is the factor levels
internally in R. Now I can take the mean of factor variable, because my
factor variable is in order.
